apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  config.json: |
    {{- $mergedConfig := merge .Values.vaultwarden.smtp.config .Values.vaultwarden.general.config .Values.vaultwarden.security.config .Values.vaultwarden.logging.config }}
    {{ $mergedConfig | toJson }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- if .Values.vaultwarden.general.websocket.enabled }}
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_ADDRESS: {{ .Values.vaultwarden.general.websocket.address | quote }}
  WEBSOCKET_PORT: {{ .Values.vaultwarden.general.websocket.port | quote }}
  {{- end }}
  DATA_FOLDER: {{ .Values.vaultwarden.storage.dataDir | quote }}
  ROCKET_PORT: {{ .Values.vaultwarden.general.rocket.port | quote }}
  ROCKET_WORKERS: {{ .Values.vaultwarden.general.rocket.workers | quote }}
  WEB_VAULT_ENABLED: {{ .Values.vaultwarden.general.webVaultEnabled | quote }}
  DB_CONNECTION_RETRIES: {{ .Values.vaultwarden.database.connectionRetries | quote }}
  DATABASE_MAX_CONNS: {{ .Values.vaultwarden.database.maxConnections | quote }}