{{ if not (and ( .Values.vaultwarden.smtp.existingSecret.name ) ( .Values.vaultwarden.security.adminToken.existingSecret.name )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if not ( .Values.vaultwarden.smtp.existingSecret.name ) }}
  SMTP_PASSWORD: {{ .Values.vaultwarden.smtp.password | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.vaultwarden.smtp.username | b64enc | quote }}
  {{- end }}
  {{- if not ( .Values.vaultwarden.security.adminToken.existingSecret.name ) }}
  ADMIN_TOKEN: {{ default "" .Values.vaultwarden.security.adminToken.value | b64enc | quote }}
  {{- end }}
{{ end }}
