apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.statefulsetlabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  serviceName: vaultwarden
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vaultwarden
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vaultwarden
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha1sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha1sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- .Values.initContainers | nindent 8 }}
        {{- end }}
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: vaultwarden
          envFrom:
            - configMapRef:
                name: {{ include "vaultwarden.fullname" . }}-env
          env:
            {{- if .Values.vaultwarden.smtp.existingSecret.username }}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.vaultwarden.smtp.existingSecret.name }}
                  key: {{ default "SMTP_USERNAME" .Values.vaultwarden.smtp.existingSecret.username.secretKey }}
            {{- end }}
            {{- if .Values.vaultwarden.smtp.existingSecret.password }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.vaultwarden.smtp.existingSecret.name }}
                  key: {{ default "SMTP_PASSWORD" .Values.vaultwarden.smtp.existingSecret.password.secretKey }}
            {{- end }}
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.vaultwarden.security.adminToken.existingSecret.name }}
                  key: {{ default "ADMIN_TOKEN" .Values.vaultwarden.security.adminToken.existingSecret.key }}
                  optional: true
            {{- if ne "default" .Values.vaultwarden.database.type }}
            - name: DATABASE_URL
              {{- if .Values.vaultwarden.database.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vaultwarden.database.existingSecret }}
                  key: {{ .Values.vaultwarden.database.existingSecretKey }}
              {{- else }}
              {{- if .Values.vaultwarden.database.uriOverride }}
              value: {{ .Values.vaultwarden.database.uriOverride }}
              {{- else }}
              value: {{ include "dbString" . | quote }}
              {{- end }}
              {{- end }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: {{ .Values.vaultwarden.general.websocket.port }}
              name: websocket
              protocol: TCP
          volumeMounts:
            - name: vaultwarden-config
              mountPath: {{ .Values.vaultwarden.storage.dataDir }}/config.json
              subPath: config.json
            {{- if .Values.vaultwarden.storage.enabled }}
            - name: vaultwarden-data
              mountPath: {{ .Values.vaultwarden.storage.dataDir }}
            {{- end }}
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      securityContext:  
        runAsUser: 1000  
        fsGroup: 1000    
        {{- if .Values.sidecars }}
        {{- toYaml .Values.sidecars | nindent 8 }}
        {{- end }}
      volumes:
        - name: vaultwarden-config
          configMap:
            name: {{ include "vaultwarden.fullname" . }}-config
  {{- if .Values.vaultwarden.storage.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden-data
        labels:
          {{- include "vaultwarden.labels" . | nindent 10 }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.vaultwarden.storage.size }}
        storageClassName: {{ default "" .Values.vaultwarden.storage.class }}
  {{- end }}
